spring.application.name=meal-choice
server.port=8080
spring.datasource.url=jdbc:mysql://localhost:3306/meal_choice?createDatabaseIfNotExist=true&useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
spring.datasource.username=root
spring.datasource.password=123456
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.open-in-view=true
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=anh2k3le@gmail.com
spring.mail.password=ornf kril abdd crcd
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

jwt.secret=6afb00b4e213a2559d33b640c84e6c027595b9e36faea41f9dc458be9eebd467
jwt.access-token-expiration=900000
jwt.refresh-token-expiration=604800000

app.base-url=http://localhost:8080
app.activation.expiration-minutes=15

spring.thymeleaf.cache=false
spring.thymeleaf.servlet.produce-partial-output-while-processing=false

spring.web.error.include-message=always
spring.web.error.include-binding-errors=always
spring.web.error.include-stacktrace=always
spring.web.error.include-exception=true

logging.level.org.springframework.web=DEBUG
logging.level.org.thymeleaf=DEBUG
heigit.api-key=eyJvcmciOiI1YjNjZTM1OTc4NTExMTAwMDFjZjYyNDgiLCJpZCI6IjNhY2Q2M2E3MTYxYzRlYTRiZGJiMTQ3ZTE2MWNiNDJlIiwiaCI6Im11cm11cjY0In0=
heigit.geocode-url=https://api.openrouteservice.org/geocode/search
heigit.directions-url=https://api.openrouteservice.org/v2/directions/driving-car
