spring.application.name=meal-choice
spring.datasource.url=jdbc:mysql://localhost:3306/meal_choice
spring.datasource.username=root
spring.datasource.password=123456

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=ngoc.ltnanh@gmail.com
spring.mail.password=ornf kril abdd crcd
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true