spring.application.name=meal_choice
spring.datasource.url=jdbc:mysql://localhost:3306/meal_choice
spring.datasource.username=root
spring.datasource.password=66668888

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
app.name=Tr?a Nay ?n Gì
app.company=Nhóm phát tri?n Tr?a Nay ?n Gì
app.email=support@truanayangi.vn
app.phone=6666 8888
app.address=Hà N?i, Vi?t Nam
app.base-url=http://localhost:8080